// tailwind.config.js
module.exports = {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "primary": "#000000",
        "on-primary": "#ffffff",
        "primary-container": "#16652A",
        "on-primary-container": "#EAE3D5",
        "primary-fixed": "#D4E9E0",
        "primary-fixed-dim": "#B4C5BE",
        "on-primary-fixed": "#0B221A",
        "on-primary-fixed-variant": "#274237",
        "inverse-primary": "#B4C5BE",
        "secondary": "#7A8F6B",
        "on-secondary": "#ffffff",
        "secondary-container": "#E3EADF",
        "on-secondary-container": "#7A8F6B",
        "secondary-fixed": "#E3EADF",
        "secondary-fixed-dim": "#B4C5A8",
        "on-secondary-fixed": "#2F3A26",
        "on-secondary-fixed-variant": "#495B3E",
        "tertiary": "#000000",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#2a1700",
        "on-tertiary-container": "#b87500",
        "tertiary-fixed": "#ffddb8",
        "tertiary-fixed-dim": "#ffb95f",
        "on-tertiary-fixed": "#2a1700",
        "on-tertiary-fixed-variant": "#653e00",
        "surface": "#FAF8F5",
        "surface-dim": "#EAE3D5",
        "surface-bright": "#FAF8F5",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#FAF8F5",
        "surface-container": "#F5F1E8",
        "surface-container-high": "#EAE3D5",
        "surface-container-highest": "#DFD9CD",
        "surface-variant": "#DFD9CD",
        "surface-tint": "#274237",
        "on-surface": "#1a1c1c",
        "on-surface-variant": "#44474d",
        "on-background": "#1a1c1c",
        "background": "#F5F1E8",
        "background-subtle": "#F1F7F4",
        "outline": "#8C867A",
        "outline-variant": "#DFD9CD",
        "inverse-surface": "#2f3131",
        "inverse-on-surface": "#f1f1f1",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "error-red": "#EF4444",
        "success-green": "#10B981",
        "whatsapp-green": "#25D366",
        "info": "#1D503A",
        "success": "#1D503A",
        "warning": "#BA7517",
        "danger": "#BA1A1A"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "8px",
        "gutter": "24px",
        "container-max": "1280px",
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        "section-gap": "120px"
      },
      fontFamily: {
        "display-lg": ["Montserrat", "sans-serif"],
        "display-lg-mobile": ["Montserrat", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }]
      }
    }
  },
  plugins: []
}
