// tailwind.config.js
module.exports = {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "primary": "#16652A",
        "on-primary": "#ffffff",
        "primary-container": "#1C190B",
        "on-primary-container": "#EEDADA",
        "primary-fixed": "#D1EED4",
        "primary-fixed-dim": "#B3DEB9",
        "on-primary-fixed": "#1C190B",
        "on-primary-fixed-variant": "#34513A",
        "inverse-primary": "#B3DEB9",
        "secondary": "#EAC784",
        "on-secondary": "#2C2712",
        "secondary-container": "#EDB868",
        "on-secondary-container": "#2C2712",
        "secondary-fixed": "#EAC784",
        "secondary-fixed-dim": "#EDB868",
        "on-secondary-fixed": "#2C2712",
        "on-secondary-fixed-variant": "#1C190B",
        "tertiary": "#2E8E9D",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#1B3B40",
        "on-tertiary-container": "#EEDADA",
        "tertiary-fixed": "#BCE3E9",
        "tertiary-fixed-dim": "#9AD2DC",
        "on-tertiary-fixed": "#1B3B40",
        "on-tertiary-fixed-variant": "#265B64",
        "surface": "#2C2712",
        "surface-dim": "#1C190B",
        "surface-bright": "#2C2712",
        "surface-container-lowest": "#1A170B",
        "surface-container-low": "#231F0E",
        "surface-container": "#2C2712",
        "surface-container-high": "#3A3418",
        "surface-container-highest": "#453E1D",
        "surface-variant": "#3A3418",
        "surface-tint": "#EAC784",
        "on-surface": "#EEDADA",
        "on-surface-variant": "#B3A69A",
        "on-background": "#EEDADA",
        "background": "#2C2712",
        "background-subtle": "#231F0E",
        "outline": "#453E1D",
        "outline-variant": "#3A3418",
        "inverse-surface": "#EEDADA",
        "inverse-on-surface": "#2C2712",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "error-red": "#EF4444",
        "success-green": "#10B981",
        "whatsapp-green": "#25D366"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "8px",
        "gutter": "24px",
        "container-max": "1280px",
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        "section-gap": "120px"
      },
      fontFamily: {
        "display-lg": ["Montserrat", "sans-serif"],
        "display-lg-mobile": ["Montserrat", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }]
      }
    }
  },
  plugins: []
}
